services:
    mongo:
        image: mongo:7
        restart: unless-stopped
        container_name: mongo
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: chat_db
        ports:
            - "27017:27017"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        depends_on:
            - mongo
        environment:
            MONGO_URL: "mongodb://mongo:27017/chat_db"
            DATABASE_NAME: "chat_db"
            PASETO_SYMMETRIC_KEY: ${PASETO_SYMMETRIC_KEY}
            ENCRYPTION_SECRET_KEY: ${ENCRYPTION_SECRET_KEY}
            CORS_ALLOWED_ORIGINS: "http://localhost:5000,http://localhost"
        ports:
            - "8000:8000"
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        depends_on:
            - backend
        environment:
            - VITE_BACKEND_BASE_URL=/api

    nginx:
        image: nginx:1.25-alpine
        container_name: nginx
        depends_on:
            - frontend
            - backend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./frontend/dist:/usr/share/nginx/html:ro
        ports:
            - "80:80"
        restart: unless-stopped

volumes:
    mongo-data:
