services:
    mongo:
        image: mongo:7
        restart: unless-stopped
        container_name: mongo
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: chat_db
        ports:
            - "27017:27017"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        depends_on:
            - mongo
        volumes:
            - ./upload:/app/uploads
        environment:
            MONGO_URI: "mongodb://mongo:27017/chat_db"
            DATABASE_NAME: "chat_db"
            PASETO_SYMMETRIC_KEY: "x@pej!w9t%g$zm7f^ka2r$n!dtvuhp*s"
            ENCRYPTION_SECRET_KEY: "s2r$n!x@pej!w9t%g$zm7f^kadtvuhp*"
            CORS_ALLOWED_ORIGINS: "http://localhost:5000,http://localhost"
        ports:
            - "8000:8000"
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        depends_on:
            - backend
        environment:
            - VITE_BACKEND_BASE_URL=/api
        ports:
            - 80:80

volumes:
    mongo-data:
